name: DevOps Proje Kontrolu

on: [push]

jobs:
  build-islemi:
    runs-on: ubuntu-latest

    steps:
      - name: Kodlari GitHub'dan cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Bagimliliklari Kur
        run: pip install flask

      - name: Testleri Calistir
        run: python test_app.py

      - name: Docker Imajini Olustur
        if: success()
        run: docker build -t test-app .
